/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.jefe;

/**
 *
 * @author Victor López
 */

import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.db.Conexion;

public class CasosAperturados extends javax.swing.JInternalFrame {
    DefaultTableModel modeloCasos = null;
    public static int bandera = 0;
    ResultSet resultado = null;
    
    static String query = "";
    
    public ArrayList<String> areas = null;
    
    ArrayList<ArrayList<String>> casos = null;
    
    Conexion conex = new Conexion();
    
    /**
     * Creates new form CasosAperturados
     */
    public CasosAperturados(ArrayList<String> areasUsuarios) throws SQLException {
        initComponents();
        
        areas = areasUsuarios;
        
        casos = new ArrayList<>();
        
        bandera = 1;
        
        Object[][] data = null;
        
        String[] columnas = { "#", "Caso", "Codigo", "Descripción", "Datos adicionales", "Programador", "Tester" };
        
        modeloCasos = new DefaultTableModel(data, columnas);
        this.CasosEnProgresojTable.setModel(modeloCasos);
        
        String sql = "SELECT caso.caso_id, solicitud.caso, caso.codigo, solicitud.descripcion, caso_descripcion, CONCAT(programadores.nombres, ' ', programadores.apellidos) AS programador, caso.fecha_limite, CONCAT(testers.nombres, ' ', testers.apellidos) AS tester, caso.fecha_registro FROM caso INNER JOIN solicitud ON solicitud.solicitud_id = caso.solicitud_id INNER JOIN usuarios AS programadores ON programadores.usuario_id = caso.programador INNER JOIN usuarios AS testers ON testers.usuario_id = caso.tester INNER JOIN departamento ON solicitud.departamento_id = departamento.departamento_id WHERE (";
        
        for (int i = 0; i < areas.size(); i++) {
            if (i == (areas.size() - 1)) {
                sql += "departamento.departamento_id = " + areas.get(i) + ")";
            } else {
                sql += "departamento.departamento_id = " + areas.get(i) + " OR ";
            }
        }
        
        query = sql;
        
        conex.setRs(sql);
        
        listarCasos();
    }
    
    private void listarCasos() throws SQLException {
        modeloCasos.setRowCount(0);
        
        resultado = conex.getRs();
        
        int i = 0;
        
        while (resultado.next()) {
            i++;
            
            Object[] newRow = {
                i, resultado.getString(2), resultado.getString(3), resultado.getString(4), resultado.getString(5), resultado.getString(6), resultado.getString(8), resultado.getString(9),
            };
            
            ArrayList<String> caso = new ArrayList<>();
            
            caso.add(resultado.getString(1));
            caso.add(resultado.getString(2));
            caso.add(resultado.getString(3));
            caso.add(resultado.getString(4));
            caso.add(resultado.getString(5));
            caso.add(resultado.getString(6));
            caso.add(resultado.getString(7));
            caso.add(resultado.getString(8));
            caso.add(resultado.getString(9));
            
            caso.add(String.valueOf(i));
            
            casos.add(caso);
            
            modeloCasos.addRow(newRow);
        }
        
        resultado.close();
    }
    
    private void mostrarDatos(ArrayList<String> info) {
        /*for (int i = 0; i < info.size(); i++) {
            System.out.println(i + " -> " + info.get(i));   
        }*/
        
        lblCodigo.setText(info.get(2));
        lblCaso.setText(info.get(1));
        txtRequerimientos.setText(info.get(3));
        txtAdicionales.setText(info.get(4));
        lblProgramador.setText(info.get(5));
        lblTester.setText(info.get(7));
        lblLimite.setText(info.get(6));
        
        btnBitacora.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CasosEnProgresojTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCaso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRequerimientos = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdicionales = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lblProgramador = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTester = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        btnBitacora = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bitacoraJTables = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        CasosEnProgresojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CasosEnProgresojTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        CasosEnProgresojTable.setName("CasosEnProgresojTable"); // NOI18N
        CasosEnProgresojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CasosEnProgresojTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CasosEnProgresojTable);

        jLabel1.setText("Buscar:");

        txtBuscar.setName("txtBuscar"); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del caso"));

        jLabel2.setText("Código:");

        lblCaso.setText("_________");

        jLabel4.setText("Caso:");

        lblCodigo.setText("_________");

        jLabel6.setText("Requerimientos:");

        txtRequerimientos.setColumns(20);
        txtRequerimientos.setRows(5);
        jScrollPane2.setViewportView(txtRequerimientos);

        jLabel7.setText("Datos tecnicos:");

        txtAdicionales.setColumns(20);
        txtAdicionales.setRows(5);
        jScrollPane3.setViewportView(txtAdicionales);

        jLabel8.setText("Programador:");

        lblProgramador.setText("_________");

        jLabel10.setText("Tester:");

        lblTester.setText("_________");

        jLabel12.setText("Fecha limite:");

        lblLimite.setText("_________");

        btnBitacora.setText("Ver bitacora");
        btnBitacora.setEnabled(false);
        btnBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitacoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProgramador, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTester, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(lblCaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 27, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBitacora)
                                .addGap(139, 139, 139))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCaso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblProgramador)
                    .addComponent(jLabel10)
                    .addComponent(lblTester))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblLimite))
                .addGap(18, 18, 18)
                .addComponent(btnBitacora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitacora"));

        bitacoraJTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(bitacoraJTables);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasosEnProgresojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasosEnProgresojTableMouseClicked
        int fila = CasosEnProgresojTable.rowAtPoint(evt.getPoint());
        
        for (int i = 0; i < casos.size(); i++) {
            if (fila == (Integer.parseInt(casos.get(i).get(9)) - 1)) {
                mostrarDatos(casos.get(i));
                break;
            }
        }
    }//GEN-LAST:event_CasosEnProgresojTableMouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        while (modeloCasos.getRowCount() != 0) modeloCasos.removeRow(0) ;

        String busqueda = txtBuscar.getText();

        String query1 = query + " AND solicitud.caso LIKE '%" + busqueda + "%' ";
        
        conex.setRs(query1);

        try {
            listarCasos();
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(AlumnosListado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitacoraActionPerformed
        String codigo = lblCodigo.getText();
        
        Object[][] datos = null;
        
        String[] columns = { "#", "Caso", "Bitacora", "Fecha" };
        
        DefaultTableModel modeloBitacora = new DefaultTableModel(datos, columns);
        this.bitacoraJTables.setModel(modeloBitacora);
        
        String query = "SELECT bitacora.bitacora_id, caso.codigo, bitacora.descripcion, bitacora.fecha_registro FROM bitacora INNER JOIN caso ON caso.caso_id = bitacora.caso_id WHERE caso.codigo = '" + codigo + "'";
        
        try {
            conex.setRs(query);
        
            modeloBitacora.setRowCount(0);

            resultado = conex.getRs();

            while (resultado.next()) {
                Object[] newRow = {
                    resultado.getString(1), resultado.getString(2), resultado.getString(3), resultado.getString(4)
            };
                
                modeloBitacora.addRow(newRow);
            }
            
            resultado.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBitacoraActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            bandera = 0;
            
            this.dispose();
            
            conex.cerrarConexion();
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(AlumnosListado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CasosEnProgresojTable;
    private javax.swing.JTable bitacoraJTables;
    private javax.swing.JButton btnBitacora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCaso;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblProgramador;
    private javax.swing.JLabel lblTester;
    private javax.swing.JTextArea txtAdicionales;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtRequerimientos;
    // End of variables declaration//GEN-END:variables
}
