/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.mdi;

/**
 *
 * @author Victor López
 */

import java.sql.*;
import sv.edu.udb.admin.*;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setExtendedState(Admin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        listadoDepaMenuItem = new javax.swing.JMenuItem();
        formDepaMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        listadoDesarrolloMenuItem = new javax.swing.JMenuItem();
        DesarrolloManteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Departamentos");

        listadoDepaMenuItem.setMnemonic('o');
        listadoDepaMenuItem.setText("Listado");
        fileMenu.add(listadoDepaMenuItem);

        formDepaMenuItem.setMnemonic('s');
        formDepaMenuItem.setText("Mantenimiento");
        fileMenu.add(formDepaMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Jefes de departamentos");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Listado");
        cutMenuItem.setToolTipText("");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Mantenimiento");
        editMenu.add(copyMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Jefes de desarrollo");

        listadoDesarrolloMenuItem.setMnemonic('c');
        listadoDesarrolloMenuItem.setText("Listado");
        listadoDesarrolloMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoDesarrolloMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(listadoDesarrolloMenuItem);

        DesarrolloManteMenuItem.setMnemonic('a');
        DesarrolloManteMenuItem.setText("Mantenimiento");
        DesarrolloManteMenuItem.setName("DesarrolloManteMenuItem"); // NOI18N
        DesarrolloManteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesarrolloManteMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(DesarrolloManteMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void listadoDesarrolloMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoDesarrolloMenuItemActionPerformed
        try {
            if (JefesDesarrolloListado.bandera == 0) {
                JefesDesarrolloListado jefesDesarrolloListado = new JefesDesarrolloListado();

                desktopPane.add(jefesDesarrolloListado);
                jefesDesarrolloListado.show();

                JefesDesarrolloListado.bandera = 1;
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listadoDesarrolloMenuItemActionPerformed

    private void DesarrolloManteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesarrolloManteMenuItemActionPerformed
        try {
            if (JefesDesarrolloMantenimiento.bandera == 0) {
                JefesDesarrolloMantenimiento jefesDesarrolloMantenimiento = new JefesDesarrolloMantenimiento();

                desktopPane.add(jefesDesarrolloMantenimiento);
                jefesDesarrolloMantenimiento.show();

                JefesDesarrolloMantenimiento.bandera = 1;
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(MDI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DesarrolloManteMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DesarrolloManteMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem formDepaMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem listadoDepaMenuItem;
    private javax.swing.JMenuItem listadoDesarrolloMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
