/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.mdi;

/**
 *
 * @author Victor López
 */

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sv.edu.udb.desarrollo.*;

public class JefeDesarrollo extends javax.swing.JFrame {

    /**
     * Creates new form JefeDesarrollo
     */
    public JefeDesarrollo() {
        initComponents();
        setExtendedState(Admin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CasosListadoMenuItem = new javax.swing.JMenuItem();
        InformeMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        ProgresoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setMaximumSize(new java.awt.Dimension(124, 32769));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Casos");

        CasosListadoMenuItem.setMnemonic('s');
        CasosListadoMenuItem.setText("Listado");
        CasosListadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasosListadoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(CasosListadoMenuItem);

        InformeMenuItem.setMnemonic('s');
        InformeMenuItem.setText("Informe");
        InformeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(InformeMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Programadores");

        ProgresoMenuItem.setMnemonic('p');
        ProgresoMenuItem.setText("Progreso");
        ProgresoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgresoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(ProgresoMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasosListadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasosListadoMenuItemActionPerformed
        if(CasoListado.bandera == 0){          
            try {
                CasoListado cl = new CasoListado();
                               
                desktopPane.add(cl);
                cl.show();
            } catch (SQLException ex) {
                Logger.getLogger(JefeAreasFuncionales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CasosListadoMenuItemActionPerformed

    private void InformeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeMenuItemActionPerformed
        if(InformesCasos.bandera == 0){          
            try {
                InformesCasos informes = new InformesCasos();
                               
                desktopPane.add(informes);
                informes.show();
            } catch (SQLException ex) {
                Logger.getLogger(InformesCasos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_InformeMenuItemActionPerformed

    private void ProgresoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgresoMenuItemActionPerformed
        if(ProgramadoresMonitoreo.bandera == 0){          
            try {
                ProgramadoresMonitoreo monitore = new ProgramadoresMonitoreo();
                               
                desktopPane.add(monitore);
                monitore.show();
            } catch (SQLException ex) {
                Logger.getLogger(ProgramadoresMonitoreo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ProgresoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JefeDesarrollo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CasosListadoMenuItem;
    private javax.swing.JMenuItem InformeMenuItem;
    private javax.swing.JMenuItem ProgresoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
