/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.mdi;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import sv.edu.udb.jefe.SolicitudesListado;

/**
 *
 * @author Victor López
 */
public class JefeAreasFuncionales extends javax.swing.JFrame {
    public static ArrayList<String> areas = new ArrayList<>();
    
    /**
     * Creates new form JefeAreasFuncionales
     */
    public JefeAreasFuncionales() {
        initComponents();
        setExtendedState(Admin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ProgresoMenu = new javax.swing.JMenu();
        SolicitudesMenuItem = new javax.swing.JMenuItem();
        RechazadasMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProgresoMenu.setMnemonic('e');
        ProgresoMenu.setText("Solicitudes");

        SolicitudesMenuItem.setMnemonic('t');
        SolicitudesMenuItem.setText("Solicitudes");
        SolicitudesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudesMenuItemActionPerformed(evt);
            }
        });
        ProgresoMenu.add(SolicitudesMenuItem);

        RechazadasMenuItem.setMnemonic('y');
        RechazadasMenuItem.setText("Rechazadas");
        ProgresoMenu.add(RechazadasMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("En progreso");
        ProgresoMenu.add(pasteMenuItem);

        menuBar.add(ProgresoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolicitudesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudesMenuItemActionPerformed
        // TODO add your handling code here:
        if(SolicitudesListado.bandera == 0){          
            try {
                SolicitudesListado SL = new SolicitudesListado(areas);
                               
                desktopPane.add(SL);
                SL.show();
            } catch (SQLException ex) {
                Logger.getLogger(JefeAreasFuncionales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SolicitudesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JefeAreasFuncionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JefeAreasFuncionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JefeAreasFuncionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JefeAreasFuncionales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JefeAreasFuncionales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ProgresoMenu;
    private javax.swing.JMenuItem RechazadasMenuItem;
    private javax.swing.JMenuItem SolicitudesMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
