/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.mdi;

/**
 *
 * @author Victor López
 */

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import sv.edu.udb.programador.*;

public class Programadores extends javax.swing.JFrame {
    public static int idProgramador = 0;
    
    /**
     * Creates new form Programadores
     */
    public Programadores() {
        initComponents();
        setExtendedState(Admin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MisCasosMenuItem = new javax.swing.JMenuItem();
        casosRechazadosMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Casos");

        MisCasosMenuItem.setMnemonic('o');
        MisCasosMenuItem.setText("Mis casos");
        MisCasosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisCasosMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(MisCasosMenuItem);

        casosRechazadosMenuItem.setMnemonic('o');
        casosRechazadosMenuItem.setText("Casos rechazados");
        casosRechazadosMenuItem.setToolTipText("");
        casosRechazadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casosRechazadosMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(casosRechazadosMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Bitacora");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Agregar");
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MisCasosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisCasosMenuItemActionPerformed
        if(CasosAsignados.bandera == 0){          
            try {
                CasosAsignados ca = new CasosAsignados(idProgramador);
                               
                desktopPane.add(ca);
                ca.show();
            } catch (SQLException ex) {
                Logger.getLogger(JefeAreasFuncionales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_MisCasosMenuItemActionPerformed

    private void casosRechazadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casosRechazadosMenuItemActionPerformed
        if(CasosRechazados.bandera == 0){          
            try {
                CasosRechazados cr = new CasosRechazados(idProgramador);
                               
                desktopPane.add(cr);
                cr.show();
            } catch (SQLException ex) {
                Logger.getLogger(JefeAreasFuncionales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_casosRechazadosMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MisCasosMenuItem;
    private javax.swing.JMenuItem casosRechazadosMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
