/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.desarrollo;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.edu.udb.db.Conexion;

/**
 *
 * @author Victor López
 */
public class InformesCasos extends javax.swing.JInternalFrame {
    DefaultTableModel modeloCasos = null;
    public static int bandera = 0;
    ResultSet resultado = null;
    
    ArrayList<ArrayList<String>> cantidades = null;
    
    Conexion conex = new Conexion();
    
    /**
     * Creates new form InformesCasos
     */
    public InformesCasos() throws SQLException {
        initComponents();
        
        Object[][] data = null;
        
        String[] columnas = { "#", "Código", "Tipo",  "Departamento", "Caso", "Requerimientos", "Datos", "Programador", "Fecha de entrega", "Estado" };
        
        modeloCasos = new DefaultTableModel(data, columnas);
        this.CasosJTable.setModel(modeloCasos);
        
        String sql1 = "SELECT caso.caso_id, caso.codigo, tipo_solicitud.tipo, departamento.departamento, solicitud.caso, solicitud.descripcion AS requerimientos, caso.caso_descripcion AS datos, CONCAT(usuarios.nombres, ' ', usuarios.apellidos) AS programador, caso.fecha_limite AS entrega, estado_caso.estado FROM caso INNER JOIN solicitud ON solicitud.solicitud_id = caso.solicitud_id INNER JOIN usuarios ON usuarios.usuario_id = caso.programador INNER JOIN estado_caso ON estado_caso.estado_caso_id = caso.estado INNER JOIN tipo_solicitud ON solicitud.tipo_solicitud = tipo_solicitud.tipo_solicitud_id INNER JOIN departamento ON solicitud.departamento_id = departamento.departamento_id ORDER BY caso.caso_id DESC";
        
        listarCasos(sql1);
        
        String sql2 = "SELECT estado_caso.estado, COUNT(caso.estado) AS Total FROM estado_caso LEFT JOIN caso ON caso.estado = estado_caso.estado_caso_id GROUP BY estado_caso.estado";
        
        cantidadCasos(sql2);
    }
    
    private void cantidadCasos(String query) throws SQLException {
        cantidades = new ArrayList<>();
        
        conex.setRs(query);
        
        ResultSet rs = conex.getRs();
        
        while (rs.next()) {
            ArrayList<String> cantidad =  new ArrayList<>();
            
            cantidad.add(rs.getString(1));
            cantidad.add(rs.getString(2));
            
            cantidades.add(cantidad);
        }
        
        rs.close();
        
        lblAsignados.setText(cantidades.get(1).get(1));
        lblAprobados.setText(cantidades.get(0).get(1));
        lblRechazados.setText(cantidades.get(2).get(1));
        lblEspera.setText(cantidades.get(3).get(1));
    }
    
    private void listarCasos(String query) throws SQLException {
        modeloCasos.setRowCount(0);
        
        conex.setRs(query);
        
        ResultSet rs = conex.getRs();
        
        while (rs.next()) {
            Object[] newRow = {
                rs.getInt(1), 
                rs.getString(2), 
                rs.getString(3), 
                rs.getString(4), 
                rs.getString(5), 
                rs.getString(6), 
                rs.getString(7), 
                rs.getString(8), 
                rs.getString(9), 
                rs.getString(10),
            };
            
            modeloCasos.addRow(newRow);
        }
        
        rs.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hastaJDate = new com.toedter.calendar.JDateChooser();
        desdeJDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAsignados = new javax.swing.JLabel();
        lblAprobados = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEspera = new javax.swing.JLabel();
        lblRechazados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CasosJTable = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conteo general"));

        jLabel5.setText("Aprobados: ");

        jLabel4.setText("Asignados:");

        lblAsignados.setText("0");

        lblAprobados.setText("0");

        jLabel6.setText("Rechazados");

        jLabel7.setText("En espera de aprobación:");

        lblEspera.setText("0");

        lblRechazados.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAprobados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAsignados)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRechazados)
                    .addComponent(lblEspera))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblAsignados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblAprobados)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblRechazados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblEspera))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CasosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CasosJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(CasosJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desdeJDate, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hastaJDate, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrar))
                            .addComponent(jLabel2))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hastaJDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desdeJDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            bandera = 0;
            
            this.dispose();
            
            conex.cerrarConexion();
        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(AlumnosListado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String desde = "", hasta = "";
        
        int error = 0;
        
        try {
            desde = new SimpleDateFormat("yyyy-MM-dd").format(desdeJDate.getDate());
            hasta = new SimpleDateFormat("yyyy-MM-dd").format(hastaJDate.getDate());
        } catch (Exception e) {
            desde = null;
            hasta = null;
        }
        
        if (desde == null || hasta == null) {
            JOptionPane.showMessageDialog(null, "Rango de fechas invalidos", "Error al filtrar", JOptionPane.ERROR_MESSAGE);
            error++;
        }
        
        if (error < 1) { 
            String sql1 = "SELECT caso.caso_id, caso.codigo, tipo_solicitud.tipo, departamento.departamento, solicitud.caso, solicitud.descripcion AS requerimientos, caso.caso_descripcion AS datos, CONCAT(usuarios.nombres, ' ', usuarios.apellidos) AS programador, caso.fecha_limite AS entrega, estado_caso.estado FROM caso INNER JOIN solicitud ON solicitud.solicitud_id = caso.solicitud_id INNER JOIN usuarios ON usuarios.usuario_id = caso.programador INNER JOIN estado_caso ON estado_caso.estado_caso_id = caso.estado INNER JOIN tipo_solicitud ON solicitud.tipo_solicitud = tipo_solicitud.tipo_solicitud_id INNER JOIN departamento ON solicitud.departamento_id = departamento.departamento_id WHERE DATE(caso.fecha_registro) BETWEEN '" + desde + "' AND '" + hasta + "' ORDER BY caso.caso_id DESC";
            
            try {
                listarCasos(sql1);
            } catch (SQLException ex) {
                Logger.getLogger(InformesCasos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CasosJTable;
    private javax.swing.JButton btnFiltrar;
    private com.toedter.calendar.JDateChooser desdeJDate;
    private com.toedter.calendar.JDateChooser hastaJDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAprobados;
    private javax.swing.JLabel lblAsignados;
    private javax.swing.JLabel lblEspera;
    private javax.swing.JLabel lblRechazados;
    // End of variables declaration//GEN-END:variables
}
